/// Left Block ///
export { default as GameBtnsReviewComment } from './LeftBlock/GameBtnsReviewComment/GameBtnsReviewComment'
export { default as GamePlatformsPlaytime } from './LeftBlock/GamePlatformsPlaytime/GamePlatformsPlaytime'
export { default as GameSysRequirements } from './LeftBlock/GameSysRequirements/GameSysRequirements'
export { default as GameButtonsRating } from './LeftBlock/GameButtonsRating/GameButtonsRating'
export { default as GameButtonsAddTo } from './LeftBlock/GameButtonsAddTo/GameButtonsAddTo'
export { default as CurrentDirectory } from './LeftBlock/CurrentDirectory/CurrentDirectory'
export { default as GameRatingScale } from './LeftBlock/GameRatingScale/GameRatingScale'
export { default as AboutTheGame } from './LeftBlock/AboutTheGame/AboutTheGame'
export { default as GameWebsite } from './LeftBlock/GameWebsite/GameWebsite'
export { default as GameName } from './LeftBlock/GameName/GameName'
/// Right Block ///
export { default as GameInfoVideoPlayer } from './RightBlock/GameInfoVideoPlayer/GameInfoVideoPlayer'
export { default as GameInfoPhotoAlbum } from './RightBlock/GameInfoPhotoAlbum/GameInfoPhotoAlbum'
export { default as GameContributors } from './RightBlock/GameContributors/GameContributors'
export { default as EditTheGameInfo } from './RightBlock/EditTheGameInfo/EditTheGameInfo'
export { default as WhereToBuyGame } from './RightBlock/WhereToBuyGame/WhereToBuyGame'
