export { NewReleases } from './NewReleases/NewReleases'
export { Platforms } from './Platforms/Platforms'
export { Browse } from './Browse/Browse'
export { Genres } from './Genres/Genres'
export { Top } from './Top/Top'
