export interface IIGameInfo {
  id: number
  meh: number
  skip: number
  name: string
  clip: string
  about: string
  buyInEG: string
  logoImg: string
  release: string
  website: string
  genres: string[]
  buyInGOG: string
  playtime: string
  fullVideo: string
  publisher: string
  developer: string
  ageRating: string
  aboutMore: string
  buyInSteam: string
  platforms: string[]
  recommended: number
  exceptional: number
  lastModified: string
  ratingMyGames: number
  allPlatforms: string[]
  categoryRating: string
  categoryGenres: string
  totalRatingName: string
  totalRatingNumber: number
  genresRatingNumber: number
  categoryRatingNumber: number
  systemRequirementsPC: string
}
