export { default as ItemIMGPlatforms } from './ItemIMGPlatforms/ItemIMGPlatforms'
export { AdditionalyInfoItem } from './AdditionalyInfoItem/AdditionalyInfoItem'
export { PlayerBackground } from './PlayerVideo/PlayerBackground'
export { PlayerPictures } from './PlayerPictures/PlayerPictures'
export { PlayerVideo } from './PlayerVideo/PlayerVideo'
